/////////////////////////////
///         AUTH           //
/////////////////////////////

export const LOGGING_IN = 'LOGGING_IN'
export const LOGOUT_USER = 'LOGOUT_USER'
export const REQUEST_USER_DETAILS = 'REQUEST_USER_DETAILS' 
export const RECEIVE_USER_DETAILS = 'RECEIVE_USER_DETAILS' 

export const REQUEST_CREATE_BOOKMARK  = 'REQUEST_CREATE_BOOKMARK'
export const CREATE_BOOKMARK_SUCCESS  = 'CREATE_BOOKMARK_SUCCESS'
export const CREATE_BOOKMARK_FAIL     = 'CREATE_BOOKMARK_FAIL'

export const REQUEST_DELETE_BOOKMARK  = 'REQUEST_DELETE_BOOKMARK'
export const DELETE_BOOKMARK_SUCCESS  = 'DELETE_BOOKMARK_SUCCESS'
export const DELETE_BOOKMARK_FAIL     = 'DELETE_BOOKMARK_FAIL'

/////////////////////////////
///         CHALLENGES           //
/////////////////////////////

export const REQUEST_CHALLENGES = 'REQUEST_CHALLENGES'
export const RECEIVE_CHALLENGES = 'RECEIVE_CHALLENGES'



//create
export const REQUEST_CREATE_RESOURCE = `REQUEST_CREATE_RESOURCE`
export const CREATE_RESOURCE_SUCCESS = `CREATE_RESOURCE_SUCCESS`
export const CREATE_RESOURCE_FAIL    = `CREATE_RESOURCE_FAIL`

//delete
export const REQUEST_REMOVE_RESOURCE = 'REQUEST_REMOVE_RESOURCE'
export const REMOVE_RESOURCE_SUCCESS = 'REMOVE_RESOURCE_SUCCESS'
export const REMOVE_RESOURCE_FAIL    = 'REMOVE_RESOURCE_FAIL'

//fetch
export const REQUEST_FETCH_RESOURCE = 'REQUEST_FETCH_RESOURCE'
export const FETCH_RESOURCE_SUCCESS = 'FETCH_RESOURCE_SUCCESS'
export const FETCH_RESOURCE_FAIL    = 'FETCH_RESOURCE_FAIL'


//upvote
export const REQUEST_CREATE_UPVOTE              = 'REQUEST_CREATE_UPVOTE'
export const CREATE_CHALLENGE_UPVOTE_SUCCESS    = 'CREATE_UPVOTE_SUCCESS'
export const CREATE_REPLY_UPVOTE_SUCCESS        = 'REQUEST_CREATE_REPLY_UPVOTE_SUCCESS'
export const CREATE_UPVOTE_FAIL                 = 'CREATE_UPVOTE_FAIL'


// user challenges and replies
export const REQUEST_USER_CHALLENGES    = 'REQUEST_USER_CHALLENGES'
export const RECEIVE_USER_CHALLENGES    = 'RECEIVE_USER_CHALLENGES'
export const REQUEST_USER_REPLIES       = 'REQUEST_USER_REPLIES'
export const RECEIVE_USER_REPLIES       = 'RECEIVE_USER_REPLIES'
export const REQUEST_USER_PROFILE       = 'REQUEST_USER_PROFILE'
export const RECEIVE_USER_PROFILE       = 'RECEIVE_USER_PROFILE'